name: Build and publish Docker image

on:
  release:
    types: [published]

env:
  IMAGE_NAME: device-os
  VERSION_FILE: version.properties

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Load DeviceOS version
        run: |
          cat ${{ env.VERSION_FILE }} >> $GITHUB_ENV
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/lucamora/${{ env.IMAGE_NAME }}
          flavor: |
            latest=true
          tags: |
            type=raw,value=${{ env.DEVICEOS_VERSION_STRING }}

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to GHCR
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            DOS_VER_STR=${{ env.DEVICEOS_VERSION_STRING }}
            DOS_VER_NUM=${{ env.DEVICEOS_VERSION_NUMBER }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}